# Generated by Django 6.0.7 on 2026-08-13 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_etudiant_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('justification', models.CharField(choices=[('demande_de_repos', 'repos maladif'), ('permission', "permission d'arrêt de cours"), ('non_justifie', 'non_justifie'), ('retard_justfie', 'retard_jstifie')], default='permission', max_length=25)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.matiere')),
            ],
        ),
    ]
