# Generated by Django 6.0.7 on 2026-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(default=12, max_length=25),
            preserve_default=False,
        ),
    ]
