# Generated by Django 6.0.7 on 2026-08-30 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_etudiant_age_etudiant_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.matiere')),
            ],
        ),
    ]
